web:
  build: .
  command: python /code/app.py
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - db
  hostname: myappserver
db:
  hostname: mysqlserver
  image: akshay2005/sems-mysql
  environment:
     MYSQL_ROOT_PASSWORD: my-secret-pw
     MYSQL_DATABASE: expensesdb
